local_backend: true

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img/
public_folder: /img/

collections:
    #Services
  - name: "services"
    label: "Services"
    folder: "src/data/theservices"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", choose_url: false, media_folder: "img/" }
    #Products 
  - name: "products"
    label: "Products"
    folder: "src/data/products"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {label: "Multiple Prices", name: "multisize", widget: "boolean", default: false }
      - label: "Sizes"
        name: "sizes" 
        widget: "list"
        summary: '{{fields.sizename}}'
        fields: 
          - {label: "Size", name: "sizename", widget: "string"}
          - { label: "Price", name: "price", widget: "string"}
      - { label: "Product code", name: "code", widget: "string" }
      - { label: "Image", name: "image", widget: "image", choose_url: false, media_folder: "img/" }
      - { label: "Category", name: "category", widget: "relation", collection: "menu", search_fields: ["subcategory.*.subname"], value_field: "subcategory.*.subname"}
      - { label: "Slug", name: "slug", widget: "relation", collection: "menu", search_fields: ["subcategory.*.slug"], value_field: "subcategory.*.slug"}
    #Menu
  - name: "menu"
    label: "Menu"
    folder: "src/data/menu"
    create: true
    fields:
      - { label: "Category", name: "category", widget: "string"}
      - label: "Subcategory"
        name: "subcategory" 
        widget: "list"
        summary: '{{fields.subname}}'
        fields: 
          - {label: Subtitle Title, name: subname, widget: string}
          - {label:  Slug, name: slug, widget: string}
    #Pages
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/data/pages/home.yaml"
        fields:
          - {label: Title, name: header, widget: string}
          - {label: Subtitle, name: underheader, widget: string}
          - {label: Title Image, name: headerImage, widget: image, choose_url: false, media_folder: "img/"}
          - label: Services
            name: services
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Slug, name: slug, widget: string}
              - {label: Description, name: description, widget: markdown}
              - {label: Image, name: image, widget: image, choose_url: false, media_folder: "img/"}
              - {label: Button, name: button, widget: string}
          - {label: Company Description, name: companyDisc, widget: markdown}
          - label: Partners
            name: partners
            widget: list
            fields:
              - {label: Image, name: image, widget: image, choose_url: false, media_folder: "img/"}
    



